{
 "title": "AppGate Sessions, Users, Sites and Traffic",
 "tags": [
  "users",
  "sessions",
  "appgate",
  "bandwidth",
  "provisioned"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "target", "query": "appliance_major_version" }
  ]
 },
 "panels": [
  {
   "title": "Total daily users & sessions $target (quantile 95 | 1 day)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(appgate:gateway_sessions_quantile_95_over_1d:number{target=\"$target\"})",
     "legendFormat": "Sessions {{target}}"
    },
    {
     "expr": "appgate:distinct_user_count_quantile_95_over_1d:number{target=\"$target\"}",
     "legendFormat": "Users {{target}}"
    }
   ]
  },
  {
   "title": "Total Bandwith $target (quantile 95 | 1day, 5min)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(appgate:bandwidth_quantile_95_over_1d:bps{target=\"$target\"})",
     "legendFormat": "Over 1 day"
    },
    {
     "expr": "sum(appgate:bandwidth_quantile_95_over_5m:bps{target=\"$target\"})",
     "legendFormat": "Over 5 minutes"
    },
    { "expr": "appga" }
   ]
  },
  {
   "title": "User and sesssions per site $target (quantile 95 | 1 hour)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " sum(appgate:gateway_sessions_quantile_95_over_1h:number{target=\"$target\"}) by (site_id)",
     "legendFormat": "Sessions {{site_id}}"
    },
    {
     "expr": "sum(appgate:distinct_user_count_quantile_95_over_1h:number{target=\"$target\"}) by (site_id)",
     "legendFormat": "Users {{site_id}}"
    },
    { "expr": "appgate:dis" }
   ]
  },
  {
   "title": "User and session per GW $target (quantile 95 | 1hour)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(appgate:gateway_sessions_quantile_95_over_1h:number{target=\"$target\"}) by (appliance_name)",
     "legendFormat": "Sessions {{appliance_name}} "
    },
    {
     "expr": "sum(appgate:distinct_user_count_quantile_95_over_1h:number{target=\"$target\"}) by (appliance_name)",
     "legendFormat": "Users  {{appliance_name}} "
    }
   ]
  },
  {
   "title": "Site Bandwith $target  (quantile 95 | 5min)",
   "type": "graph",
   "description": "95th percentile over 10minutes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(appgate:bandwidth_quantile_95_over_5m:bps) by (site_id)\n",
     "legendFormat": "{{site_id}}"
    }
   ]
  },
  {
   "title": "GW Bandwidth (quantile 95 | 5min)",
   "type": "graph",
   "description": "95th percentile / 10min",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(appgate:bandwidth_quantile_95_over_5m:bps) by (appliance_name)",
     "legendFormat": "{{appliance_name}} "
    }
   ]
  },
  {
   "title": "IOT Bandwidth",
   "type": "graph",
   "description": "95th percentile over 10 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "appgate:bandwidth_quantile_95_over_5m:bps{role_iotconnector=\"true\", target=\"$target\"}",
     "legendFormat": "{{appliance_name}}"
    }
   ]
  }
 ]
}