{
 "title": "AppGate Appliances",
 "description": "Appliance information, resource usage",
 "tags": [
  "appliances",
  "appgate",
  "provisioned",
  "resources"
 ],
 "time": { "from": "2020-05-06T19:21:57.038Z", "to": "2020-05-07T05:59:39.403Z" },
 "templating": {
  "list": [
   { "name": "target", "query": "appliance_major_version" }
  ]
 },
 "panels": [
  {
   "title": "CPU usage (5min avg)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "appgate:appliance_cpu_avg_5m:percent{target=\"$target\"}",
     "legendFormat": "{{appliance_name}}"
    }
   ]
  },
  {
   "title": "Appliance Version",
   "type": "table",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "appgate:appliance_version_count:labels_to_table{target=\"$target\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Appliance Details",
   "type": "table",
   "gridPos": { "h": 19, "w": 11, "x": 13, "y": 5 },
   "targets": [
    {
     "expr": "sum(role_status_logforwarder{role_logforwarder=\"true\", target=\"$target\"}) by (details, appliance_name, site_id)",
     "legendFormat": "logfwd"
    },
    {
     "expr": "sum(role_status_controller{role_controller=\"true\", target=\"$target\"})by (details, appliance_name,site_id)",
     "legendFormat": "ctlr"
    },
    {
     "expr": "sum(role_status_gateway{role_gateway=\"true\", target=\"$target\"})by (details, appliance_name, site_id)",
     "legendFormat": "gw"
    },
    {
     "expr": "sum(role_status_logserver{role_logserver=\"true\", target=\"$target\"})by (details, appliance_name, site_id)",
     "legendFormat": "log"
    },
    {
     "expr": "sum(role_status_iotconnector{role_iotconnector=\"true\", target=\"$target\"})by (details, appliance_name)",
     "legendFormat": "iot"
    }
   ]
  },
  {
   "title": "MEM usage (5min avg)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "appgate:appliance_memory_usage_avg_5m:percent{target=\"$target\"}",
     "legendFormat": "{{appliance_name}}"
    }
   ]
  },
  {
   "title": "Disk usage (5min avg)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "appgate:appliance_disk_usage_avg_5m:percent{target=\"$target\"}",
     "legendFormat": "{{appliance_name}}"
    }
   ]
  },
  {
   "title": "Site degradation in %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "appgate:site_degradation:percentage",
     "legendFormat": "{{site_id}} lost {{appliance_name}}, site loss"
    }
   ]
  },
  {
   "title": "Appliance offline",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(appliance_status_online{online=\"false\", target=\"$target\"}) by (appliance_name) ",
     "legendFormat": "{{appliance_name}} "
    }
   ]
  }
 ]
}