{
 "title": "AppGate Dashboard",
 "tags": [
  "appgate",
  "dashboard",
  "provisioned"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "target", "query": "appliance_major_version" }
  ]
 },
 "panels": [
  { "title": "Appliance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CTLs",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "100 * count(appliance_status_online{online=\"true\", target=\"$target\", role_controller=\"true\"})  / count(appliance_status_online{ target=\"$target\", role_controller=\"true\"}) "
    }
   ]
  },
  {
   "title": "CTLs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(controller_count{target=\"$target\"})",
     "legendFormat": "controller"
    }
   ]
  },
  {
   "title": "Appl",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(appliance_count{target=\"$target\"})",
     "legendFormat": "Appliances"
    }
   ]
  },
  {
   "title": "Off",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(appliance_status_online{target=\"$target\", online=\"false\"})",
     "legendFormat": "Offline"
    }
   ]
  },
  {
   "title": "Deact",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(appliance_activated{target=\"$target\", appliance_activated=\"false\"})",
     "legendFormat": "Offline"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 16, "w": 5, "x": 10, "y": 1 } },
  {
   "title": "Conkolla Health",
   "type": "table",
   "description": "Conkolla not 200 resp code",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "count(connection_roundtrip{target=\"$target\", http_response_code!~\"2.*\"}) by (http_response_code)",
     "legendFormat": "{{http_response_code}}"
    },
    {
     "expr": "absent(connection_roundtrip{target=\"$target\", http_response_code!~\"2.*\"})-2",
     "legendFormat": "OK"
    }
   ]
  },
  {
   "title": "Users",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(session_distinct_user_count{target=\"$target\"})"
    }
   ]
  },
  {
   "title": "Sys bandwidth",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(quantile_over_time(0.95, appliance_network_tx_bps[2m])) + sum(quantile_over_time(0.95, appliance_network_rx_bps[2m]))"
    }
   ]
  },
  {
   "title": "Sites",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 4, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": " count(count by (site_id) (appliance_status_online) )"
    },
    { "expr": "app" }
   ]
  },
  {
   "title": "Sessions",
   "type": "graph",
   "gridPos": { "h": 13, "w": 9, "x": 15, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(gateway_nr_sessions{target=\"$target\"})",
     "legendFormat": "GW sessions"
    },
    {
     "expr": "sum(session_distinct_user_count{target=\"$target\"})",
     "legendFormat": "distinct users"
    }
   ]
  },
  {
   "title": "GWs",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "100 * count(appliance_status_online{online=\"true\", target=\"$target\", role_gateway=\"true\"})  / count(appliance_status_online{ target=\"$target\", role_gateway=\"true\"}) "
    }
   ]
  },
  {
   "title": "GWs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(gateway_count{})", "legendFormat": "gateways" }
   ]
  },
  {
   "title": "AppGate Version",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 4, "y": 5 },
   "targets": [
    {
     "expr": "count_values(\"version\", appliance_major_version*100 + appliance_minor_version*10 + appliance_patch_version) by (target)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "LOG",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "100 * count(appliance_status_online{online=\"true\", target=\"$target\", role_logserver=\"true\"})  / count(appliance_status_online{ target=\"$target\", role_logserver=\"true\"}) "
    }
   ]
  },
  {
   "title": "LOG",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(logserver_count{target=\"$target\"})",
     "legendFormat": "logserver"
    }
   ]
  },
  {
   "title": "Issues",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 4, "y": 10 },
   "targets": [
    {
     "expr": "role_status_appliance{target=\"$target\", health=\"busy\"} +1",
     "legendFormat": "{{appliance_name}} "
    },
    {
     "expr": "role_status_appliance{target=\"$target\", health=\"warning\"} +4",
     "legendFormat": "{{appliance_name}} "
    },
    {
     "expr": "role_status_appliance{target=\"$target\", health=\"error\"} +12",
     "legendFormat": "{{appliance_name}} "
    },
    {
     "expr": "appliance_status_online{target=\"$target\", online=\"false\"} + 8",
     "legendFormat": "{{appliance_name}}"
    }
   ]
  },
  {
   "title": "IOT",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "100 * count(appliance_status_online{online=\"true\", target=\"$target\", role_iotconnector=\"true\"})  / count(appliance_status_online{ target=\"$target\", role_iotconnector=\"true\"}) "
    }
   ]
  },
  {
   "title": "IOT ",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(iotconnector_count{target=\"$target\"})",
     "legendFormat": "IOTcon"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Dropped packages 5 min avg",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(appliance_network_dropin{target=\"$target\"}[5m]) ",
     "legendFormat": "IN {{appliance_name}} {{busiest_nic}}"
    },
    {
     "expr": "- increase(appliance_network_dropout{target=\"$target\"}[5m]) ",
     "legendFormat": "OUT {{appliance_name}} {{busiest_nic}}"
    }
   ]
  },
  { "title": "Time series", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } }
 ]
}