{
 "title": "Conkolla",
 "tags": [
  "conkolla",
  "exporter",
  "provisioned"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Conkolla",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "conkolla_instance" }
   ]
  },
  {
   "title": "Conkolla connection duration last 5min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "conkolla:connection_total_duration_max_rate_5m:seconds ",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Exported Targets",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 4 },
   "targets": [
    {
     "expr": "count(gateway_count) by (target)"
    }
   ]
  },
  {
   "title": "Job  'conkolla' scrapes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg (promhttp_metric_handler_requests_total{job=\"conkolla\"})"
    }
   ]
  },
  {
   "title": "Conkolla uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 6 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - avg(process_start_time_seconds{job=\"conkolla\"})"
    }
   ]
  },
  {
   "title": "Open file descriptros",
   "type": "singlestat",
   "description": "Counts the number of files in /proc/PID/fd directory. This shows currently open regular files, sockets, pseudo terminals, etc.",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "process_open_fds{job=\"conkolla\"}"
    }
   ]
  },
  {
   "title": "Go routines",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "go_goroutines{job=\"conkolla\"}",
     "legendFormat": "nr go routines conkolla "
    }
   ]
  },
  {
   "title": "Conkolla virtual memory",
   "type": "singlestat",
   "description": "process_virtual_memory_bytes – uses vsize – virtual memory size is the amount of address space that a process is managing. This includes all types of memory, both in RAM and swapped out.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"conkolla\"}"
    }
   ]
  },
  {
   "title": "conkolla RSS",
   "type": "singlestat",
   "description": "multiplies rss – resident set memory size is number of memory pages the process has in real memory, with pagesize. This results in the amount of memory that belongs specifically to that process in bytes. This excludes swapped out memory pages.",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 12 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"conkolla\"}"
    }
   ]
  },
  {
   "title": "Conkolla CPU rate",
   "type": "singlestat",
   "description": "calculates the  (CPU-usage-duration)/Xminutes, e.g a ration between 0..1,",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 12 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"conkolla\"}[5m])",
     "legendFormat": "conkolla"
    }
   ]
  }
 ]
}